name: kiibati_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  sizer: ^2.0.15
  provider: ^6.0.5
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.17.0
  timeago: ^3.3.0
  video_player: ^2.7.0
  audioplayers: ^4.0.0
  url_launcher: ^6.1.12
  cached_network_image: ^3.2.3
  encrypt: ^5.0.1
  uuid: ^3.0.7
  flutter_paystack: ^1.0.7

  # firebase packages
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_messaging: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
