// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE_GlL4ui8fikzBABU7qJeGcz_QGVePu0',
    appId: '1:388882673516:web:80c82c12fa36d1f6a74d49',
    messagingSenderId: '388882673516',
    projectId: 'kiibati-3ea86',
    authDomain: 'kiibati-3ea86.firebaseapp.com',
    storageBucket: 'kiibati-3ea86.appspot.com',
    measurementId: 'G-L56Q33ZS2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVe-9gRTMZKox-ccx-z3oxKWJrXGqEr2g',
    appId: '1:388882673516:android:e557ffceeb11ddc7a74d49',
    messagingSenderId: '388882673516',
    projectId: 'kiibati-3ea86',
    storageBucket: 'kiibati-3ea86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJRJ1KIP4kdo1kqEbhWKK9i18N4fYrLo',
    appId: '1:388882673516:ios:6d86321db2fa51d3a74d49',
    messagingSenderId: '388882673516',
    projectId: 'kiibati-3ea86',
    storageBucket: 'kiibati-3ea86.appspot.com',
    iosClientId: '388882673516-vlrls70tb8j1852idkn9gcf995o43q0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiibatiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJRJ1KIP4kdo1kqEbhWKK9i18N4fYrLo',
    appId: '1:388882673516:ios:ba88653154b438b3a74d49',
    messagingSenderId: '388882673516',
    projectId: 'kiibati-3ea86',
    storageBucket: 'kiibati-3ea86.appspot.com',
    iosClientId: '388882673516-7q8v310fa9gjfv0kvcbqs6j87534rch1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiibatiMobile.RunnerTests',
  );
}
